
services:
  - type: web
    name: rogue-runner-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_TITLE
        value: "Rogue Runner - Advanced Trading Bot"
